#!/usr/bin/env python3
"""Subset Noto Serif SC (SIL OFL 1.1) to exactly the characters used by the film.

Collects every non-ASCII character that appears in film/film.js and film/index.html,
asks Google Fonts for a subset containing just those glyphs, and writes
film/fonts.js with the fonts embedded as data URLs (so the film works offline
and renders identically in the headless exporter).
"""
import base64, pathlib, re, urllib.parse, urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = [ROOT / 'film' / 'film.js', ROOT / 'film' / 'index.html']
UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36'

chars = set()
for f in SRC:
    if f.exists():
        chars |= {c for c in f.read_text(encoding='utf-8') if ord(c) > 0x2000}
chars |= set('0123456789:./ FADING')
text = ''.join(sorted(chars))
print(f'{len(chars)} glyphs')

out = ['/* Noto Serif SC subset, SIL Open Font License 1.1. Generated by tools/build_fonts.py */',
       'window.FILM_FONTS = {']
for weight in (300, 500):
    q = urllib.parse.quote(text)
    css_url = f'https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@{weight}&text={q}'
    css = urllib.request.urlopen(urllib.request.Request(css_url, headers={'User-Agent': UA})).read().decode()
    url = re.search(r'url\((https://[^)]+)\)', css).group(1)
    data = urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA})).read()
    print(weight, len(data), 'bytes')
    out.append(f"  '{weight}': 'data:font/woff2;base64,{base64.b64encode(data).decode()}',")
out.append('};')
(ROOT / 'film' / 'fonts.js').write_text('\n'.join(out) + '\n', encoding='utf-8')
