#!/usr/bin/env python3
"""Subset the films' fonts (all SIL OFL 1.1) to exactly the characters each film uses.

    python3 tools/build_fonts.py                 # film/        (褪色 · FADING)
    python3 tools/build_fonts.py first-sight     # first-sight/ (初见 · FIRST SIGHT)

Collects every non-ASCII character that appears in the film's sources, asks Google
Fonts for a subset containing just those glyphs, and writes <film>/fonts.js with the
fonts embedded as data URLs (so the film works offline and renders identically in
the headless exporter).
"""
import base64, pathlib, re, sys, urllib.parse, urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36'

# film dir -> (global name, [(family css name, weight, key)], extra characters)
FILMS = {
    'film': ('FILM_FONTS', [('Noto Serif SC', 300, '300'), ('Noto Serif SC', 500, '500')], '0123456789:./ FADING'),
    'first-sight': ('FS_FONTS', [('Noto Serif SC', 300, 'serif300'), ('Noto Serif SC', 600, 'serif600'),
                                 ('Ma Shan Zheng', 400, 'brush')], '0123456789,:./ FIRSTGH'),
}

film = sys.argv[1] if len(sys.argv) > 1 else 'film'
name, fonts, extra = FILMS[film]
src = [p for p in (ROOT / film).rglob('*') if p.suffix in ('.js', '.html') and p.name != 'fonts.js']

chars = set()
for f in src:
    chars |= {c for c in f.read_text(encoding='utf-8') if ord(c) > 0x2000}
chars |= set(extra)
text = ''.join(sorted(chars))
print(f'{len(chars)} glyphs from {len(src)} files')

out = [f'/* Font subsets (SIL Open Font License 1.1). Generated by tools/build_fonts.py */', f'window.{name} = {{']
for family, weight, key in fonts:
    q = urllib.parse.quote(text)
    fam = family.replace(' ', '+')
    css_url = f'https://fonts.googleapis.com/css2?family={fam}:wght@{weight}&text={q}'
    css = urllib.request.urlopen(urllib.request.Request(css_url, headers={'User-Agent': UA})).read().decode()
    url = re.search(r'url\((https://[^)]+)\)', css).group(1)
    data = urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA})).read()
    print(family, weight, len(data), 'bytes')
    out.append(f"  '{key}': 'data:font/woff2;base64,{base64.b64encode(data).decode()}',")
out.append('};')
(ROOT / film / 'fonts.js').write_text('\n'.join(out) + '\n', encoding='utf-8')
