#!/usr/bin/env python3
"""Subset Noto Serif SC / Noto Sans SC (SIL OFL 1.1) to exactly the characters a film uses.

    python3 tools/build_fonts.py                 # film/      → serif 300, 500
    python3 tools/build_fonts.py missyou --sans  # missyou/   → serif 300, 500 + sans 400, 500

Collects every non-ASCII character that appears in the film's .js and .html sources,
asks Google Fonts for a subset containing just those glyphs, and writes <dir>/fonts.js
with the fonts embedded as data URLs (so the film works offline and renders
identically in the headless exporter).

Keys in window.FILM_FONTS: '300' / '500' for the serif (kept for film/), and
'sans400' / 'sans500' for the sans when --sans is given.
"""
import base64, pathlib, re, sys, urllib.parse, urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
args = [a for a in sys.argv[1:] if not a.startswith('--')]
DIR = ROOT / (args[0] if args else 'film')
SANS = '--sans' in sys.argv
UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36'

chars = set()
for f in sorted(DIR.glob('*.js')) + sorted(DIR.glob('*.html')):
    if f.name == 'fonts.js':
        continue
    chars |= {c for c in f.read_text(encoding='utf-8') if ord(c) > 0x2000}
chars |= set('0123456789:./ ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz')
text = ''.join(sorted(chars))
print(f'{len(chars)} glyphs')

faces = [('Noto+Serif+SC', 300, '300'), ('Noto+Serif+SC', 500, '500')]
if SANS:
    faces += [('Noto+Sans+SC', 400, 'sans400'), ('Noto+Sans+SC', 500, 'sans500')]

out = ['/* Noto Serif SC / Noto Sans SC subsets, SIL Open Font License 1.1. Generated by tools/build_fonts.py */',
       'window.FILM_FONTS = {']
for family, weight, key in faces:
    q = urllib.parse.quote(text)
    css_url = f'https://fonts.googleapis.com/css2?family={family}:wght@{weight}&text={q}'
    css = urllib.request.urlopen(urllib.request.Request(css_url, headers={'User-Agent': UA})).read().decode()
    url = re.search(r'url\((https://[^)]+)\)', css).group(1)
    data = urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA})).read()
    print(key, len(data), 'bytes')
    out.append(f"  '{key}': 'data:font/woff2;base64,{base64.b64encode(data).decode()}',")
out.append('};')
(DIR / 'fonts.js').write_text('\n'.join(out) + '\n', encoding='utf-8')
